/* Generated By:JavaCC: Do not edit this line. ASMParseConstants.java */
package br.jabuti.instrumenter;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ASMParseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int LBRACE = 8;
  /** RegularExpression Id. */
  int RBRACE = 9;
  /** RegularExpression Id. */
  int LBRACKET = 10;
  /** RegularExpression Id. */
  int RBRACKET = 11;
  /** RegularExpression Id. */
  int SEMICOLON = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int DOT = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int GT = 16;
  /** RegularExpression Id. */
  int LT = 17;
  /** RegularExpression Id. */
  int HOOK = 18;
  /** RegularExpression Id. */
  int COLON = 19;
  /** RegularExpression Id. */
  int EQ = 20;
  /** RegularExpression Id. */
  int LE = 21;
  /** RegularExpression Id. */
  int GE = 22;
  /** RegularExpression Id. */
  int NE = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int STAR = 26;
  /** RegularExpression Id. */
  int SLASH = 27;
  /** RegularExpression Id. */
  int REM = 28;
  /** RegularExpression Id. */
  int POWER = 29;
  /** RegularExpression Id. */
  int FIELD = 30;
  /** RegularExpression Id. */
  int LOCAL = 31;
  /** RegularExpression Id. */
  int PRIVATE = 32;
  /** RegularExpression Id. */
  int PROTECTED = 33;
  /** RegularExpression Id. */
  int PUBLIC = 34;
  /** RegularExpression Id. */
  int DEFAUL = 35;
  /** RegularExpression Id. */
  int CASE = 36;
  /** RegularExpression Id. */
  int AALOAD = 37;
  /** RegularExpression Id. */
  int AASTORE = 38;
  /** RegularExpression Id. */
  int ACONST_NULL = 39;
  /** RegularExpression Id. */
  int ALOAD = 40;
  /** RegularExpression Id. */
  int ALOAD_0 = 41;
  /** RegularExpression Id. */
  int ALOAD_1 = 42;
  /** RegularExpression Id. */
  int ALOAD_2 = 43;
  /** RegularExpression Id. */
  int ANEWARRAY = 44;
  /** RegularExpression Id. */
  int ARETURN = 45;
  /** RegularExpression Id. */
  int ARRAYLENGTH = 46;
  /** RegularExpression Id. */
  int ASTORE = 47;
  /** RegularExpression Id. */
  int ASTORE_0 = 48;
  /** RegularExpression Id. */
  int ASTORE_1 = 49;
  /** RegularExpression Id. */
  int ASTORE_2 = 50;
  /** RegularExpression Id. */
  int ATHROW = 51;
  /** RegularExpression Id. */
  int BALOAD = 52;
  /** RegularExpression Id. */
  int BASTORE = 53;
  /** RegularExpression Id. */
  int BIPUSH = 54;
  /** RegularExpression Id. */
  int BREAKPOINT = 55;
  /** RegularExpression Id. */
  int CALOAD = 56;
  /** RegularExpression Id. */
  int CASTORE = 57;
  /** RegularExpression Id. */
  int CHECKCAST = 58;
  /** RegularExpression Id. */
  int D2F = 59;
  /** RegularExpression Id. */
  int D2I = 60;
  /** RegularExpression Id. */
  int D2L = 61;
  /** RegularExpression Id. */
  int DADD = 62;
  /** RegularExpression Id. */
  int DALOAD = 63;
  /** RegularExpression Id. */
  int DASTORE = 64;
  /** RegularExpression Id. */
  int DCMPG = 65;
  /** RegularExpression Id. */
  int DCMPL = 66;
  /** RegularExpression Id. */
  int DCONST = 67;
  /** RegularExpression Id. */
  int DCONST_0 = 68;
  /** RegularExpression Id. */
  int DCONST_1 = 69;
  /** RegularExpression Id. */
  int DDIV = 70;
  /** RegularExpression Id. */
  int DLOAD = 71;
  /** RegularExpression Id. */
  int DMUL = 72;
  /** RegularExpression Id. */
  int DNEG = 73;
  /** RegularExpression Id. */
  int DREM = 74;
  /** RegularExpression Id. */
  int DRETURN = 75;
  /** RegularExpression Id. */
  int DSUB = 76;
  /** RegularExpression Id. */
  int DUP = 77;
  /** RegularExpression Id. */
  int DUP_X1 = 78;
  /** RegularExpression Id. */
  int DUP_X2 = 79;
  /** RegularExpression Id. */
  int DUP2 = 80;
  /** RegularExpression Id. */
  int DUP2_X1 = 81;
  /** RegularExpression Id. */
  int DUP2_X2 = 82;
  /** RegularExpression Id. */
  int F2D = 83;
  /** RegularExpression Id. */
  int F2I = 84;
  /** RegularExpression Id. */
  int F2L = 85;
  /** RegularExpression Id. */
  int FADD = 86;
  /** RegularExpression Id. */
  int FALOAD = 87;
  /** RegularExpression Id. */
  int FASTORE = 88;
  /** RegularExpression Id. */
  int FCMPG = 89;
  /** RegularExpression Id. */
  int FCMPL = 90;
  /** RegularExpression Id. */
  int FCONST = 91;
  /** RegularExpression Id. */
  int FCONST_0 = 92;
  /** RegularExpression Id. */
  int FCONST_1 = 93;
  /** RegularExpression Id. */
  int FCONST_2 = 94;
  /** RegularExpression Id. */
  int FDIV = 95;
  /** RegularExpression Id. */
  int FLOAD = 96;
  /** RegularExpression Id. */
  int FMUL = 97;
  /** RegularExpression Id. */
  int FNEG = 98;
  /** RegularExpression Id. */
  int FREM = 99;
  /** RegularExpression Id. */
  int FRETURN = 100;
  /** RegularExpression Id. */
  int FSTORE = 101;
  /** RegularExpression Id. */
  int FSUB = 102;
  /** RegularExpression Id. */
  int GETFIELD = 103;
  /** RegularExpression Id. */
  int GETSTATIC = 104;
  /** RegularExpression Id. */
  int GOTO = 105;
  /** RegularExpression Id. */
  int GOTO_W = 106;
  /** RegularExpression Id. */
  int I2B = 107;
  /** RegularExpression Id. */
  int I2C = 108;
  /** RegularExpression Id. */
  int I2D = 109;
  /** RegularExpression Id. */
  int I2F = 110;
  /** RegularExpression Id. */
  int I2L = 111;
  /** RegularExpression Id. */
  int I2S = 112;
  /** RegularExpression Id. */
  int IADD = 113;
  /** RegularExpression Id. */
  int IALOAD = 114;
  /** RegularExpression Id. */
  int IAND = 115;
  /** RegularExpression Id. */
  int IASTORE = 116;
  /** RegularExpression Id. */
  int ICONST = 117;
  /** RegularExpression Id. */
  int ICONST_0 = 118;
  /** RegularExpression Id. */
  int ICONST_1 = 119;
  /** RegularExpression Id. */
  int ICONST_2 = 120;
  /** RegularExpression Id. */
  int ICONST_3 = 121;
  /** RegularExpression Id. */
  int ICONST_4 = 122;
  /** RegularExpression Id. */
  int ICONST_5 = 123;
  /** RegularExpression Id. */
  int ICONST_M1 = 124;
  /** RegularExpression Id. */
  int IDIV = 125;
  /** RegularExpression Id. */
  int IF_ACMPEQ = 126;
  /** RegularExpression Id. */
  int IF_ACMPNE = 127;
  /** RegularExpression Id. */
  int IF_ICMPEQ = 128;
  /** RegularExpression Id. */
  int IF_ICMPGE = 129;
  /** RegularExpression Id. */
  int IF_ICMPGT = 130;
  /** RegularExpression Id. */
  int IF_ICMPLE = 131;
  /** RegularExpression Id. */
  int IF_ICMPLT = 132;
  /** RegularExpression Id. */
  int IF_ICMPNE = 133;
  /** RegularExpression Id. */
  int IFEQ = 134;
  /** RegularExpression Id. */
  int IFGE = 135;
  /** RegularExpression Id. */
  int IFGT = 136;
  /** RegularExpression Id. */
  int IFLE = 137;
  /** RegularExpression Id. */
  int IFLT = 138;
  /** RegularExpression Id. */
  int IFNE = 139;
  /** RegularExpression Id. */
  int IFNONNULL = 140;
  /** RegularExpression Id. */
  int IFNULL = 141;
  /** RegularExpression Id. */
  int IINC = 142;
  /** RegularExpression Id. */
  int ILOAD = 143;
  /** RegularExpression Id. */
  int ILOAD_0 = 144;
  /** RegularExpression Id. */
  int ILOAD_1 = 145;
  /** RegularExpression Id. */
  int ILOAD_2 = 146;
  /** RegularExpression Id. */
  int IMPDEP_1 = 147;
  /** RegularExpression Id. */
  int IMPDEP_2 = 148;
  /** RegularExpression Id. */
  int IMUL = 149;
  /** RegularExpression Id. */
  int INEG = 150;
  /** RegularExpression Id. */
  int INSTANCEOF = 151;
  /** RegularExpression Id. */
  int INVOKEINTERFACE = 152;
  /** RegularExpression Id. */
  int INVOKESPECIAL = 153;
  /** RegularExpression Id. */
  int INVOKESTATIC = 154;
  /** RegularExpression Id. */
  int INVOKEVIRTUAL = 155;
  /** RegularExpression Id. */
  int IOR = 156;
  /** RegularExpression Id. */
  int IREM = 157;
  /** RegularExpression Id. */
  int IRETURN = 158;
  /** RegularExpression Id. */
  int ISHL = 159;
  /** RegularExpression Id. */
  int ISHR = 160;
  /** RegularExpression Id. */
  int ISTORE = 161;
  /** RegularExpression Id. */
  int ISTORE_0 = 162;
  /** RegularExpression Id. */
  int ISTORE_1 = 163;
  /** RegularExpression Id. */
  int ISTORE_2 = 164;
  /** RegularExpression Id. */
  int ISUB = 165;
  /** RegularExpression Id. */
  int IUSHR = 166;
  /** RegularExpression Id. */
  int IXOR = 167;
  /** RegularExpression Id. */
  int JSR = 168;
  /** RegularExpression Id. */
  int JSR_W = 169;
  /** RegularExpression Id. */
  int L2D = 170;
  /** RegularExpression Id. */
  int L2F = 171;
  /** RegularExpression Id. */
  int L2I = 172;
  /** RegularExpression Id. */
  int LADD = 173;
  /** RegularExpression Id. */
  int LALOAD = 174;
  /** RegularExpression Id. */
  int LAND = 175;
  /** RegularExpression Id. */
  int LASTORE = 176;
  /** RegularExpression Id. */
  int LCMP = 177;
  /** RegularExpression Id. */
  int LCONST = 178;
  /** RegularExpression Id. */
  int LCONST_0 = 179;
  /** RegularExpression Id. */
  int LCONST_1 = 180;
  /** RegularExpression Id. */
  int LDC = 181;
  /** RegularExpression Id. */
  int LDC_W = 182;
  /** RegularExpression Id. */
  int LDC2_W = 183;
  /** RegularExpression Id. */
  int LDIV = 184;
  /** RegularExpression Id. */
  int LLOAD = 185;
  /** RegularExpression Id. */
  int LMUL = 186;
  /** RegularExpression Id. */
  int LNEG = 187;
  /** RegularExpression Id. */
  int LOOKUPSWITCH = 188;
  /** RegularExpression Id. */
  int LOR = 189;
  /** RegularExpression Id. */
  int LREM = 190;
  /** RegularExpression Id. */
  int LRETURN = 191;
  /** RegularExpression Id. */
  int LSHL = 192;
  /** RegularExpression Id. */
  int LSHR = 193;
  /** RegularExpression Id. */
  int LSTORE = 194;
  /** RegularExpression Id. */
  int LSUB = 195;
  /** RegularExpression Id. */
  int LUSHR = 196;
  /** RegularExpression Id. */
  int LXOR = 197;
  /** RegularExpression Id. */
  int MONITORENTER = 198;
  /** RegularExpression Id. */
  int MONITOREXIT = 199;
  /** RegularExpression Id. */
  int MULTIANEWARRAY = 200;
  /** RegularExpression Id. */
  int NEW = 201;
  /** RegularExpression Id. */
  int NEWARRAY = 202;
  /** RegularExpression Id. */
  int NOP = 203;
  /** RegularExpression Id. */
  int POP = 204;
  /** RegularExpression Id. */
  int POP2 = 205;
  /** RegularExpression Id. */
  int PUSH = 206;
  /** RegularExpression Id. */
  int PUTFIELD = 207;
  /** RegularExpression Id. */
  int PUTSTATIC = 208;
  /** RegularExpression Id. */
  int RET = 209;
  /** RegularExpression Id. */
  int RETURN = 210;
  /** RegularExpression Id. */
  int SALOAD = 211;
  /** RegularExpression Id. */
  int SASTORE = 212;
  /** RegularExpression Id. */
  int SIPUSH = 213;
  /** RegularExpression Id. */
  int SWAP = 214;
  /** RegularExpression Id. */
  int TABLESWITCH = 215;
  /** RegularExpression Id. */
  int WIDE = 216;
  /** RegularExpression Id. */
  int FIXED_POINT_LITERAL = 217;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 218;
  /** RegularExpression Id. */
  int STRING_LITERAL = 219;
  /** RegularExpression Id. */
  int IDENTIFIER = 220;
  /** RegularExpression Id. */
  int LETTER = 221;
  /** RegularExpression Id. */
  int DIGIT = 222;
  /** RegularExpression Id. */
  int PARAM = 223;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
    "\"field\"",
    "\"local\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"default\"",
    "\"case\"",
    "\"AALOAD\"",
    "\"AASTORE\"",
    "\"ACONST_NULL\"",
    "\"ALOAD\"",
    "\"ALOAD_0\"",
    "\"ALOAD_1\"",
    "\"ALOAD_2\"",
    "\"ANEWARRAY\"",
    "\"ARETURN\"",
    "\"ARRAYLENGTH\"",
    "\"ASTORE\"",
    "\"ASTORE_0\"",
    "\"ASTORE_1\"",
    "\"ASTORE_2\"",
    "\"ATHROW\"",
    "\"BALOAD\"",
    "\"BASTORE\"",
    "\"BIPUSH\"",
    "\"BREAKPOINT\"",
    "\"CALOAD\"",
    "\"CASTORE\"",
    "\"CHECKCAST\"",
    "\"D2F\"",
    "\"D2I\"",
    "\"D2L\"",
    "\"DADD\"",
    "\"DALOAD\"",
    "\"DASTORE\"",
    "\"DCMPG\"",
    "\"DCMPL\"",
    "\"DCONST\"",
    "\"DCONST_0\"",
    "\"DCONST_1\"",
    "\"DDIV\"",
    "\"DLOAD\"",
    "\"DMUL\"",
    "\"DNEG\"",
    "\"DREM\"",
    "\"DRETURN\"",
    "\"DSUB\"",
    "\"DUP\"",
    "\"DUP_X1\"",
    "\"DUP_X2\"",
    "\"DUP2\"",
    "\"DUP2_X1\"",
    "\"DUP2_X2\"",
    "\"F2D\"",
    "\"F2I\"",
    "\"F2L\"",
    "\"FADD\"",
    "\"FALOAD\"",
    "\"FASTORE\"",
    "\"FCMPG\"",
    "\"FCMPL\"",
    "\"FCONST\"",
    "\"FCONST_0\"",
    "\"FCONST_1\"",
    "\"FCONST_2\"",
    "\"FDIV\"",
    "\"FLOAD\"",
    "\"FMUL\"",
    "\"FNEG\"",
    "\"FREM\"",
    "\"FRETURN\"",
    "\"FSTORE\"",
    "\"FSUB\"",
    "\"GETFIELD\"",
    "\"GETSTATIC\"",
    "\"GOTO\"",
    "\"GOTO_W\"",
    "\"I2B\"",
    "\"I2C\"",
    "\"I2D\"",
    "\"I2F\"",
    "\"I2L\"",
    "\"I2S\"",
    "\"IADD\"",
    "\"IALOAD\"",
    "\"IAND\"",
    "\"IASTORE\"",
    "\"ICONST\"",
    "\"ICONST_0\"",
    "\"ICONST_1\"",
    "\"ICONST_2\"",
    "\"ICONST_3\"",
    "\"ICONST_4\"",
    "\"ICONST_5\"",
    "\"ICONST_M1\"",
    "\"IDIV\"",
    "\"IF_ACMPEQ\"",
    "\"IF_ACMPNE\"",
    "\"IF_ICMPEQ\"",
    "\"IF_ICMPGE\"",
    "\"IF_ICMPGT\"",
    "\"IF_ICMPLE\"",
    "\"IF_ICMPLT\"",
    "\"IF_ICMPNE\"",
    "\"IFEQ\"",
    "\"IFGE\"",
    "\"IFGT\"",
    "\"IFLE\"",
    "\"IFLT\"",
    "\"IFNE\"",
    "\"IFNONNULL\"",
    "\"IFNULL\"",
    "\"IINC\"",
    "\"ILOAD\"",
    "\"ILOAD_0\"",
    "\"ILOAD_1\"",
    "\"ILOAD_2\"",
    "\"IMPDEP_1\"",
    "\"IMPDEP_2\"",
    "\"IMUL\"",
    "\"INEG\"",
    "\"INSTANCEOF\"",
    "\"INVOKEINTERFACE\"",
    "\"INVOKESPECIAL\"",
    "\"INVOKESTATIC\"",
    "\"INVOKEVIRTUAL\"",
    "\"IOR\"",
    "\"IREM\"",
    "\"IRETURN\"",
    "\"ISHL\"",
    "\"ISHR\"",
    "\"ISTORE\"",
    "\"ISTORE_0\"",
    "\"ISTORE_1\"",
    "\"ISTORE_2\"",
    "\"ISUB\"",
    "\"IUSHR\"",
    "\"IXOR\"",
    "\"JSR\"",
    "\"JSR_W\"",
    "\"L2D\"",
    "\"L2F\"",
    "\"L2I\"",
    "\"LADD\"",
    "\"LALOAD\"",
    "\"LAND\"",
    "\"LASTORE\"",
    "\"LCMP\"",
    "\"LCONST\"",
    "\"LCONST_0\"",
    "\"LCONST_1\"",
    "\"LDC\"",
    "\"LDC_W\"",
    "\"LDC2_W\"",
    "\"LDIV\"",
    "\"LLOAD\"",
    "\"LMUL\"",
    "\"LNEG\"",
    "\"LOOKUPSWITCH\"",
    "\"LOR\"",
    "\"LREM\"",
    "\"LRETURN\"",
    "\"LSHL\"",
    "\"LSHR\"",
    "\"LSTORE\"",
    "\"LSUB\"",
    "\"LUSHR\"",
    "\"LXOR\"",
    "\"MONITORENTER\"",
    "\"MONITOREXIT\"",
    "\"MULTIANEWARRAY\"",
    "\"NEW\"",
    "\"NEWARRAY\"",
    "\"NOP\"",
    "\"POP\"",
    "\"POP2\"",
    "\"PUSH\"",
    "\"PUTFIELD\"",
    "\"PUTSTATIC\"",
    "\"RET\"",
    "\"RETURN\"",
    "\"SALOAD\"",
    "\"SASTORE\"",
    "\"SIPUSH\"",
    "\"SWAP\"",
    "\"TABLESWITCH\"",
    "\"WIDE\"",
    "<FIXED_POINT_LITERAL>",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<PARAM>",
  };

}
